### What You're Aiming For

This ➡️ dataset contains banking marketing campaign data and we can use it to optimize marketing campaigns to attract more customers to term deposit subscription.

What is a Term Deposit?

A Term deposit is a deposit that a bank or a financial institution offers with a fixed rate (often better than just opening deposit account) in which your money will be returned back at a specific maturity time.


### Instructions

In this assignment you will have to take the following steps:

    - Import your dataset and perform initial analysis and visualization
    - Clean the data
    - Build a  deep learning network to predict the marketing campaign outcome ("deposit" either Yes or No)
    - You have to submit a jupyter notebook file. 

- Link : Get started with Google Colab 

Please make sure it's a public shareable link.

In [ ]:
import numpy as np
import pandas as pd

#import standard visualization
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [21]:
df = pd.read_csv("bank (1).csv")

In [22]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  11162 non-null  float64
 1   balance              11162 non-null  float64
 2   duration             11162 non-null  float64
 3   campaign             11162 non-null  float64
 4   deposit              11162 non-null  float64
 5   job_admin.           11162 non-null  float64
 6   job_blue-collar      11162 non-null  float64
 7   job_entrepreneur     11162 non-null  float64
 8   job_housemaid        11162 non-null  float64
 9   job_management       11162 non-null  float64
 10  job_retired          11162 non-null  float64
 11  job_self-employed    11162 non-null  float64
 12  job_services         11162 non-null  float64
 13  job_student          11162 non-null  float64
 14  job_technician       11162 non-null  float64
 15  job_unemployed       11162 non-null  float64
 16  job_unknown          11162 non-null  float64
 17  marital_divorced     11162 non-null  float64
 18  marital_married      11162 non-null  float64
 19  marital_single       11162 non-null  float64
 20  education_primary    11162 non-null  float64
 21  education_secondary  11162 non-null  float64
 22  education_tertiary   11162 non-null  float64
 23  education_unknown    11162 non-null  float64
 24  housing_no           11162 non-null  float64
 25  housing_yes          11162 non-null  float64
 26  loan_no              11162 non-null  float64
 27  loan_yes             11162 non-null  float64
dtypes: float64(28)
memory usage: 2.4 MB

In [15]:
df.describe(include = "object").T

           count unique         top  freq
job        11162     12  management  2566
marital    11162      3     married  6351
education  11162      4   secondary  5476
housing    11162      2          no  5881
loan       11162      2          no  9702
deposit    11162      2          no  5873

In [ ]:
df.describe().T

In [23]:
df = df.drop("default", axis = 1)
df = df.drop("contact", axis = 1)
df = df.drop("month", axis = 1)
df = df.drop("poutcome", axis = 1)
df = df.drop("pdays", axis = 1)
df = df.drop("day", axis = 1)
df = df.drop("previous", axis = 1)

In [16]:
df = df.drop_duplicates().reset_index(drop=True)

In [24]:
df["deposit"] = label_encoder.fit_transform(df["deposit"])

In [25]:
df = pd.get_dummies(df, drop_first = False)

In [26]:
df

,age,balance,duration,campaign,deposit,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,...,marital_married,marital_single,education_primary,education_secondary,education_tertiary,education_unknown,housing_no,housing_yes,loan_no,loan_yes
0,59,2343,1042,1,1,True,False,False,False,False,...,True,False,False,True,False,False,False,True,True,False
1,56,45,1467,1,1,True,False,False,False,False,...,True,False,False,True,False,False,True,False,True,False
2,41,1270,1389,1,1,False,False,False,False,False,...,True,False,False,True,False,False,False,True,True,False
3,55,2476,579,1,1,False,False,False,False,False,...,True,False,False,True,False,False,False,True,True,False
4,54,184,673,2,1,True,False,False,False,False,...,True,False,False,False,True,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,1,257,1,0,False,True,False,False,False,...,False,True,True,False,False,False,False,True,True,False
11158,39,733,83,4,0,False,False,False,False,False,...,True,False,False,True,False,False,True,False,True,False
11159,32,29,156,2,0,False,False,False,False,False,...,False,True,False,True,False,False,True,False,True,False
11160,43,0,9,2,0,False,False,False,False,False,...,True,False,False,True,False,False,True,False,False,True
11161,34,0,628,1,0,False,False,False,False,False,...,True,False,False,True,False,False,True,False,True,False

In [40]:
bool_cols = df.select_dtypes(include='bool').columns  # Get names of all boolean columns
df[bool_cols] = df[bool_cols].astype(int)

In [47]:
# Get names of all integer columns
int_cols = df.select_dtypes(include='int').columns  

# Convert all integer columns to float
df[int_cols] = df[int_cols].astype(float)

In [61]:
import tensorflow as tf  # TensorFlow library for building neural networks
from tensorflow.keras.models import Sequential  # Sequential model for building a feedforward neural network
from tensorflow.keras.layers import Dense  # Dense layer for fully connected layers
from sklearn.datasets import fetch_california_housing  # California Housing dataset
from sklearn.model_selection import train_test_split  # Function to split data into training and test sets
from sklearn.preprocessing import StandardScaler

In [50]:
# Convert the entire DataFrame to float32
# Convert all columns except the target column to a NumPy array
X = df.drop(columns=['deposit']).astype(np.float32).to_numpy()  # Exclude 'deposit' column
y = df['deposit'].astype(int).to_numpy()  # Target variable

In [62]:
# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data (normalize features) so they have a mean of 0 and variance of 1.
# This is important for better convergence in neural networks.
scaler = StandardScaler()  # Create an instance of the StandardScaler
X_train = scaler.fit_transform(X_train)  # Fit on training data and apply the transformation
X_test = scaler.transform(X_test)  # Apply the same transformation to test data (without fitting again)

In [31]:
from keras.models import Sequential  # Sequential model to define a feedforward neural network
from keras.layers import Dense

In [29]:
len(X.columns)

27

In [55]:
from keras.models import Sequential
from keras.layers import Dense, Input

# Create a Sequential model
model = Sequential()

# Use Input layer to define input shape
model.add(Input(shape=(27,)))  # Define input shape explicitly

# Add Dense layers
model.add(Dense(64, activation='relu'))  # First hidden layer
model.add(Dense(32, activation='relu'))  # Second hidden layer
model.add(Dense(1, activation='sigmoid'))  # For binary classification

In [56]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [63]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.5543 - loss: 27.1078 - val_accuracy: 0.6131 - val_loss: 2.3333
Epoch 2/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5876 - loss: 2.4369 - val_accuracy: 0.6495 - val_loss: 1.3436
Epoch 3/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6260 - loss: 1.2784 - val_accuracy: 0.6517 - val_loss: 0.9037
Epoch 4/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6429 - loss: 0.9462 - val_accuracy: 0.6428 - val_loss: 0.8080
Epoch 5/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6523 - loss: 0.7895 - val_accuracy: 0.6753 - val_loss: 0.7214
Epoch 6/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6620 - loss: 0.7198 - val_accuracy: 0.6825 - val_loss: 0.6832
Epoch 7/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6729 - loss: 0.6760 - val_accuracy: 0.6702 - val_loss: 0.6887
Epoch 8/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6842 - loss: 0.6603 - val_accuracy: 0.7004 - val_loss: 0.6422
Epoch 9/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6900 - loss: 0.6244 - val_accuracy: 0.7060 - val_loss: 0.6201
Epoch 10/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6940 - loss: 0.6142 - val_accuracy: 0.7111 - val_loss: 0.6152
Epoch 11/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7048 - loss: 0.6017 - val_accuracy: 0.7016 - val_loss: 0.6186
Epoch 12/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7063 - loss: 0.5859 - val_accuracy: 0.7307 - val_loss: 0.5852
Epoch 13/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7264 - loss: 0.5640 - val_accuracy: 0.7380 - val_loss: 0.5796
Epoch 14/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7260 - loss: 0.5765 - val_accuracy: 0.7195 - val_loss: 0.5992
Epoch 15/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7232 - loss: 0.5503 - val_accuracy: 0.7424 - val_loss: 0.5700
Epoch 16/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7335 - loss: 0.5602 - val_accuracy: 0.7531 - val_loss: 0.5742
Epoch 17/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7448 - loss: 0.5282 - val_accuracy: 0.7643 - val_loss: 0.5485
Epoch 18/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7560 - loss: 0.5334 - val_accuracy: 0.7531 - val_loss: 0.5574
Epoch 19/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7579 - loss: 0.5360 - val_accuracy: 0.7615 - val_loss: 0.5424
Epoch 20/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7590 - loss: 0.5152 - val_accuracy: 0.7542 - val_loss: 0.5668
Epoch 21/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7716 - loss: 0.5003 - val_accuracy: 0.7688 - val_loss: 0.5288
Epoch 22/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7739 - loss: 0.4936 - val_accuracy: 0.7615 - val_loss: 0.5432
Epoch 23/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7649 - loss: 0.5109 - val_accuracy: 0.7576 - val_loss: 0.5552
Epoch 24/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7821 - loss: 0.4776 - val_accuracy: 0.7637 - val_loss: 0.5338
Epoch 25/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7661 - loss: 0.4963 - val_accuracy: 0.7688 - val_loss: 0.5256
Epoch 26/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7706 - loss: 0.4819 - val_accuracy: 0.7632 - val_loss: 0.5229
Epoch 27/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7801 - loss: 0.4792 - val_accuracy: 0.7716 - val_loss: 0.5292
Epoch 28/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7783 - loss: 0.4789 - val_accuracy: 0.7732 - val_loss: 0.5128
Epoch 29/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7790 - loss: 0.4778 - val_accuracy: 0.7766 - val_loss: 0.5228
Epoch 30/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7758 - loss: 0.4724 - val_accuracy: 0.7732 - val_loss: 0.5180
Epoch 31/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7865 - loss: 0.4637 - val_accuracy: 0.7732 - val_loss: 0.5201
Epoch 32/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7693 - loss: 0.4897 - val_accuracy: 0.7727 - val_loss: 0.5160
Epoch 33/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7753 - loss: 0.4793 - val_accuracy: 0.7704 - val_loss: 0.5203
Epoch 34/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7949 - loss: 0.4603 - val_accuracy: 0.7738 - val_loss: 0.5148
Epoch 35/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7828 - loss: 0.4651 - val_accuracy: 0.7783 - val_loss: 0.5041
Epoch 36/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7809 - loss: 0.4795 - val_accuracy: 0.7772 - val_loss: 0.5109
Epoch 37/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7786 - loss: 0.4727 - val_accuracy: 0.7699 - val_loss: 0.5106
Epoch 38/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7826 - loss: 0.4678 - val_accuracy: 0.7632 - val_loss: 0.5189
Epoch 39/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7877 - loss: 0.4623 - val_accuracy: 0.7688 - val_loss: 0.5071
Epoch 40/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7885 - loss: 0.4603 - val_accuracy: 0.7654 - val_loss: 0.5159
Epoch 41/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7761 - loss: 0.4783 - val_accuracy: 0.7676 - val_loss: 0.5109
Epoch 42/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7840 - loss: 0.4608 - val_accuracy: 0.7749 - val_loss: 0.5197
Epoch 43/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7841 - loss: 0.4675 - val_accuracy: 0.7772 - val_loss: 0.5144
Epoch 44/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7826 - loss: 0.4650 - val_accuracy: 0.7772 - val_loss: 0.5168
Epoch 45/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7925 - loss: 0.4566 - val_accuracy: 0.7777 - val_loss: 0.5025
Epoch 46/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7787 - loss: 0.4668 - val_accuracy: 0.7760 - val_loss: 0.4999
Epoch 47/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7909 - loss: 0.4556 - val_accuracy: 0.7744 - val_loss: 0.5128
Epoch 48/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7884 - loss: 0.4579 - val_accuracy: 0.7794 - val_loss: 0.5008
Epoch 49/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7903 - loss: 0.4529 - val_accuracy: 0.7542 - val_loss: 0.5521
Epoch 50/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7967 - loss: 0.4586 - val_accuracy: 0.7783 - val_loss: 0.5213
Epoch 51/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7762 - loss: 0.4615 - val_accuracy: 0.7766 - val_loss: 0.5166
Epoch 52/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7864 - loss: 0.4601 - val_accuracy: 0.7693 - val_loss: 0.5280
Epoch 53/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7866 - loss: 0.4516 - val_accuracy: 0.7643 - val_loss: 0.5222
Epoch 54/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7804 - loss: 0.4670 - val_accuracy: 0.7643 - val_loss: 0.5209
Epoch 55/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7821 - loss: 0.4530 - val_accuracy: 0.7721 - val_loss: 0.5096
Epoch 56/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7956 - loss: 0.4452 - val_accuracy: 0.7676 - val_loss: 0.5130
Epoch 57/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7891 - loss: 0.4552 - val_accuracy: 0.7783 - val_loss: 0.5097
Epoch 58/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7892 - loss: 0.4618 - val_accuracy: 0.7710 - val_loss: 0.5122
Epoch 59/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7978 - loss: 0.4480 - val_accuracy: 0.7800 - val_loss: 0.5023
Epoch 60/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7937 - loss: 0.4489 - val_accuracy: 0.7772 - val_loss: 0.5109
Epoch 61/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7995 - loss: 0.4465 - val_accuracy: 0.7777 - val_loss: 0.5083
Epoch 62/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8018 - loss: 0.4402 - val_accuracy: 0.7811 - val_loss: 0.5149
Epoch 63/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7905 - loss: 0.4461 - val_accuracy: 0.7777 - val_loss: 0.5066
Epoch 64/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7876 - loss: 0.4594 - val_accuracy: 0.7816 - val_loss: 0.5052
Epoch 65/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7838 - loss: 0.4651 - val_accuracy: 0.7699 - val_loss: 0.5204
Epoch 66/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8017 - loss: 0.4384 - val_accuracy: 0.7732 - val_loss: 0.5163
Epoch 67/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7953 - loss: 0.4421 - val_accuracy: 0.7777 - val_loss: 0.5084
Epoch 68/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7914 - loss: 0.4486 - val_accuracy: 0.7844 - val_loss: 0.5064
Epoch 69/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7954 - loss: 0.4439 - val_accuracy: 0.7783 - val_loss: 0.5160
Epoch 70/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7945 - loss: 0.4486 - val_accuracy: 0.7749 - val_loss: 0.5118
Epoch 71/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8012 - loss: 0.4315 - val_accuracy: 0.7800 - val_loss: 0.5058
Epoch 72/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7923 - loss: 0.4487 - val_accuracy: 0.7710 - val_loss: 0.5237
Epoch 73/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7967 - loss: 0.4508 - val_accuracy: 0.7721 - val_loss: 0.5119
Epoch 74/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8003 - loss: 0.4370 - val_accuracy: 0.7822 - val_loss: 0.5152
Epoch 75/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8002 - loss: 0.4336 - val_accuracy: 0.7755 - val_loss: 0.5088
Epoch 76/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8003 - loss: 0.4378 - val_accuracy: 0.7783 - val_loss: 0.5118
Epoch 77/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8076 - loss: 0.4289 - val_accuracy: 0.7693 - val_loss: 0.5135
Epoch 78/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7909 - loss: 0.4534 - val_accuracy: 0.7738 - val_loss: 0.5240
Epoch 79/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7987 - loss: 0.4406 - val_accuracy: 0.7788 - val_loss: 0.5055
Epoch 80/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7940 - loss: 0.4401 - val_accuracy: 0.7777 - val_loss: 0.5083
Epoch 81/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7983 - loss: 0.4289 - val_accuracy: 0.7738 - val_loss: 0.5176
Epoch 82/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8007 - loss: 0.4328 - val_accuracy: 0.7777 - val_loss: 0.5248
Epoch 83/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7946 - loss: 0.4453 - val_accuracy: 0.7794 - val_loss: 0.5148
Epoch 84/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7952 - loss: 0.4399 - val_accuracy: 0.7839 - val_loss: 0.5091
Epoch 85/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8035 - loss: 0.4246 - val_accuracy: 0.7783 - val_loss: 0.5188
Epoch 86/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8025 - loss: 0.4293 - val_accuracy: 0.7744 - val_loss: 0.5196
Epoch 87/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8047 - loss: 0.4284 - val_accuracy: 0.7788 - val_loss: 0.5106
Epoch 88/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7896 - loss: 0.4450 - val_accuracy: 0.7777 - val_loss: 0.5133
Epoch 89/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7951 - loss: 0.4438 - val_accuracy: 0.7710 - val_loss: 0.5184
Epoch 90/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7960 - loss: 0.4344 - val_accuracy: 0.7704 - val_loss: 0.5170
Epoch 91/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7986 - loss: 0.4348 - val_accuracy: 0.7721 - val_loss: 0.5236
Epoch 92/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7941 - loss: 0.4459 - val_accuracy: 0.7760 - val_loss: 0.5222
Epoch 93/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8062 - loss: 0.4282 - val_accuracy: 0.7704 - val_loss: 0.5270
Epoch 94/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8022 - loss: 0.4331 - val_accuracy: 0.7794 - val_loss: 0.5146
Epoch 95/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7977 - loss: 0.4309 - val_accuracy: 0.7772 - val_loss: 0.5125
Epoch 96/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7977 - loss: 0.4336 - val_accuracy: 0.7693 - val_loss: 0.5293
Epoch 97/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8049 - loss: 0.4314 - val_accuracy: 0.7699 - val_loss: 0.5174
Epoch 98/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7982 - loss: 0.4379 - val_accuracy: 0.7682 - val_loss: 0.5267
Epoch 99/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8090 - loss: 0.4240 - val_accuracy: 0.7716 - val_loss: 0.5240
Epoch 100/100
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8047 - loss: 0.4269 - val_accuracy: 0.7760 - val_loss: 0.5176

In [58]:
predictions = model.predict(X)
print(predictions)

349/349 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
[[8.9470476e-01]
 [9.1576976e-01]
 [9.3911213e-01]
 ...
 [3.9752894e-09]
 [0.0000000e+00]
 [6.6831553e-01]]

In [59]:
print(y)

[1 1 1 ... 0 0 0]

In [64]:
mse = model.evaluate(X_test, y_test)
print(f'Mean Squared Error on Test Set: {mse}')

70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7593 - loss: 0.5544
Mean Squared Error on Test Set: [0.5332458019256592, 0.7675772309303284]